trigger:
- master

pool:
  vmImage: 'windows-latest'
steps:
- task: SpecFlowPlus@0
  inputs:
    projectFilePath: '*/Feature'
    projectName: 'livedoc'
    testExecutionJson: '**\TestExecution.json'
    projectLanguage: 'en'